version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
      POSTGRES_DB: test-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    command: air
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - air_config:/app/tmp
    depends_on:
      - postgres
    networks:
      - app-net
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: test-user
      DB_PASSWORD: test-pass
      DB_NAME: test-db

volumes:
  pg_data:
  air_config:

networks:
  app-net:
    driver: bridge
